# File              : mkdocs.yml
# Author            : JCHRYS <jchrys@me.com>
# Date              : 15.08.2019
# Last Modified Date: 22.08.2019
# Last Modified By  : JCHRYS <jchrys@me.com>
# Main
site_name: ICPC.NINJA
site_description: 'Solutions to Competitive Programming Problems'
site_author: 'JCHRYS'
site_url: 'https://icpc.ninja'

# Repo
repo_name: 'jchrys/icpc'
repo_url: 'https://github.com/jchrys/icpc'


# Theme
theme:
  name: 'material'
  language: 'en'

# CDN Dependencies
extra_css:
  - 'css/katex.css'
  - 'https://cdn.jsdelivr.net/npm/katex@0.10.2/dist/katex.min.css'
extra_javascript:
  - 'js/katex.js'
  - 'https://cdn.jsdelivr.net/npm/katex@0.10.2/dist/katex.min.js'
  - 'https://cdn.jsdelivr.net/npm/katex@0.10.2/dist/contrib/auto-render.min.js'

# pymdownx
markdown_extensions:
  - toc:
      permalink: true
      separator: _
  - codehilite:
      linenums: true
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.gemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_png
      alt: short
      options:
          attributes: 
              align: absmiddle
              height: 20px
              width: 20px
          image_path: 'https://github.com/images/icons/emoji/unicode/'
          non_standard_image_path: 'https://github.com/images/icons/emoji/'
  - admonition
  - footnotes
  - meta

# Copyright
copyright: 'jchrys &copy;2019~'

# disqus
extra:
    disqus: 'icpcninja'
# google analytics
google_analytics:
  - 'UA-144755317-1'
  - 'auto'


# dev
#dev_addr: '172.20.10.2:8080'


# TABLE OF CONTENTS
nav:
    - Home: index.md
    - Algorithms: 
        - Graph: 
            - Basics: Algorithms/Graph/Basics.md
            - Graph Traversal: Algorithms/Graph/GraphTraversal.md
            - Shortest Paths: 
                - Preface: Algorithms/Graph/ShortestPaths/Preface.md
                - Bellman-Ford: Algorithms/Graph/ShortestPaths/Bellman-Ford.md
                - Dijkstra: Algorithms/Graph/ShortestPaths/Dijkstra.md
                - Floyd-Warshall: Algorithms/Graph/ShortestPaths/Floyd-Warshall.md
        - DFS: 
            - Preface: Algorithms/Graph/DFS/Preface.md
            - DFSTree: Algorithms/Graph/DFS/Tree.md
            - StartingFinishingTime: Algorithms/Graph/DFS/StartingFinishingTime.md
            - FindingCutEdges: Algorithms/Graph/DFS/FindingCutEdges.md
        - Tree: 
            - Basics: Algorithms/Tree/Basics.md
            - Traversal : Algorithms/Tree/Traversal.md
            - DP: Algorithms/Tree/DP.md
            - SpanningTree: Algorithms/Tree/SpanningTree.md
        - Sort:
            - InsertionSort: Algorithms/Sort/InsertionSort.md
            - BubbleSort: Algorithms/Sort/BubbleSort.md
        - Euclidean: Algorithms/EuclideanAlgorithm.md
        - FastPower: Algorithms/FastPower.md
    - DataStructures: 
        - Linear:
            - Stack: DataStructures/Linear/Stack.md
            - Vector: DataStructures/Linear/Vector.md
            - Linked List: DataStructures/Linear/LinkedList.md
        - Hash Tables:
            - Preface: DataStructures/HashTables/Preface.md
            - Hash Functions: DataStructures/HashTables/HashFunctions.md
        - Trees:
            - SearchTree: DataStructures/Trees/SearchTree.md
            - BST: DataStructures/Trees/BST.md 
            - RedBlackTree: DataStructures/Trees/RedBlackTree.md
    - MISC:
        Lemma: MISC/Lemma.md
    - Language: 
        Preface: Language/Preface.md
        Keywords: Language/Keywords.md
        Class: Language/Class.md
    - Contribute:
        - HowToContribute: Contribute/HowToContribute.md
        - CodeOfConduct: Contribute/CodeOfConduct.md
        - Template: Contribute/Template.md
        - Emoji: Contribute/Emoji.md
